In [1]:
import numpy as np

In [2]:
import random
import time
import numpy as np
a = []
for i in range(100000000):
    a.append(random.random())
t1 = time.time()
sum1=sum(a)
t2=time.time()

b=np.array(a)
t4=time.time()
sum3=np.sum(b)
t5=time.time()
print(t2-t1, t5-t4)

1.740056037902832 0.16251587867736816


In [3]:
a = [1,2,3,4]
b = np.array(a)
print(type(a))
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
b.dtype

dtype('int64')

In [5]:
b.ndim

1

In [6]:
b.size

4

In [7]:
b.shape

(4,)

In [15]:
c = np.array([[[1,2,3,4],[4,5,6,7]], [[1,2,3,4],[4,5,6,7]]])

In [16]:
c.size

16

In [17]:
c.shape

(2, 2, 4)

In [18]:
arr = np.ones([10, 10])

In [19]:
arr

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [20]:
arr2 = np.zeros([10, 10])

In [21]:
arr2

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [22]:
a = np.zeros([3,4])

In [23]:
b = np.array(a)

In [24]:
b

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [25]:
c = np.asarray(a)

In [26]:
c

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [27]:
a[0] = 1

In [28]:
a

array([[ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [29]:
b

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [30]:
c

array([[ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [31]:
np.random.rand(10)

array([ 0.63959885,  0.71034892,  0.42400312,  0.03862671,  0.04082053,
        0.2320093 ,  0.93647996,  0.37947259,  0.50155337,  0.97395727])

In [39]:
arr = np.random.normal(1.75, 0.1, (3,4))

In [40]:
arr

array([[ 1.62185471,  1.67591946,  1.7761369 ,  1.68331896],
       [ 1.83925878,  1.77582642,  1.83012776,  1.94824228],
       [ 1.6649081 ,  1.70986971,  1.79448272,  1.75714413]])

In [50]:
arr[0:3:2, 0:2]

array([[ 1.62185471,  1.67591946],
       [ 1.6649081 ,  1.70986971]])

In [62]:
one = np.ones([24])

In [64]:
# 修改形状的时候，注意元素数量匹配
one.reshape([3, 9])

ValueError: cannot reshape array of size 24 into shape (3,9)

In [69]:
a = np.array([[80,86],
[82,80],
[85,78],
[90,90],
[86,82],
[82,90],
[78,80],
[92,94]])

In [70]:
type(a)

numpy.ndarray

In [74]:
a[:, 1] > 80

array([ True, False, False,  True,  True,  True, False,  True], dtype=bool)

In [76]:
# 统计运算，得出所以学生平时成绩的最大值，最小值0 列 ,1 行
np.amin(a, axis=1)

array([80, 80, 78, 90, 82, 82, 78, 92])

In [77]:
np.mean(a, axis=0)

array([ 84.375,  85.   ])

In [79]:
a * 10

array([[800, 860],
       [820, 800],
       [850, 780],
       [900, 900],
       [860, 820],
       [820, 900],
       [780, 800],
       [920, 940]])

In [80]:
a + 1

array([[81, 87],
       [83, 81],
       [86, 79],
       [91, 91],
       [87, 83],
       [83, 91],
       [79, 81],
       [93, 95]])

In [81]:
a = np.array([[1,2,3,4]])

In [85]:
b = np.array([[2],[2],[2],[2]])

In [86]:
b.shape

(4, 1)

In [87]:
a * b

array([[2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8]])

In [88]:
# 矩阵运算
a = np.array([[80,86],
[82,80],
[85,78],
[90,90],
[86,82],
[82,90],
[78,80],
[92,94]])

b = np.array([[0.3], [0.7]])
np.dot(a, b)

array([[ 84.2],
       [ 80.6],
       [ 80.1],
       [ 90. ],
       [ 83.2],
       [ 87.6],
       [ 79.4],
       [ 93.4]])

In [92]:
np.genfromtxt("./data/test/test.csv", delimiter=',')

array([[   nan,    nan,    nan,    nan],
       [   1. ,  123. ,    1.4,   23. ],
       [   2. ,  110. ,    nan,   18. ],
       [   3. ,    nan,    2.1,   19. ]])

In [93]:
# 关于nan
type(np.nan)

float

In [ ]:
'?'  --> np.nan